# Generated by Django 4.1.5 on 2023-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='TextContent',
        ),
        migrations.AddField(
            model_name='note',
            name='jsonContent',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
