# Generated by Django 4.1.5 on 2023-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_text_note_textcontent_note_jsoncontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='TextContent',
        ),
        migrations.RemoveField(
            model_name='note',
            name='jsonContent',
        ),
        migrations.AddField(
            model_name='note',
            name='rawText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
