# Generated by Django 4.1.5 on 2023-02-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_note_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='important',
            new_name='starMarked',
        ),
    ]
