# Generated by Django 4.1.5 on 2023-03-23 20:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_basictoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthenticationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 23, 21, 57, 36, 740398))),
                ('uuid', models.UUIDField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BasicToken',
        ),
    ]
