# Generated by Django 4.1.5 on 2023-03-23 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_emailauthenticationtoken_delete_basictoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='expire_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 23, 21, 58, 41, 139972)),
        ),
    ]
