# Generated by Django 4.1.5 on 2023-03-23 21:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_emailauthenticationtoken_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='expire_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 23, 22, 17, 52, 496114)),
        ),
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eca6ab01-4bf4-41c7-8b74-5e086312c643'), editable=False),
        ),
    ]
