# Generated by Django 4.1.5 on 2023-03-23 21:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_emailauthenticationtoken_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='expire_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 23, 22, 18, 48, 95134)),
        ),
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
