# Generated by Django 4.1.5 on 2023-03-23 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_emailauthenticationtoken_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthenticationtoken',
            name='expire_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 23, 23, 2, 29, 675594)),
        ),
    ]
